apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
  labels:
    app: html
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
  template:
    metadata:
      labels:
        app: html
    spec:
      containers:
      - name: html
        image: kaique5247/front:1.1
        ports:
        - containerPort: 5000
